AllCops:
  DisplayCopNames: true
  NewCops: enable
  # No need for TargetRubyVersion. Rubocop checks for .ruby-version to get it.
  # https://docs.rubocop.org/rubocop/0.85/configuration.html#setting-the-target-ruby-version

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  # TODO: re-enable
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashAsLastArrayItem:
  EnforcedStyle: braces

Style/HashTransformValues:
  Enabled: true

Layout/HashAlignment:
  Enabled: false

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/LineLength:
  Enabled: false
  Max: 180

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Max: 30
  Exclude:
    - lib/capistrano/tasks/*.rake

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/PercentLiteralDelimiters:
  # Specify the default preferred delimiter for all types with the 'default' key
  # Override individual delimiters (even with default specified) by specifying
  # an individual key
  PreferredDelimiters:
    default: ()
    '%i': '()'
    '%I': '()'
    '%r': '{}'
    '%w': '()'
    '%W': '()'

Bundler/OrderedGems:
  Enabled: false

Naming/FileName:
  Exclude:
    - "config/**/*"
    - "app/views/**/*"

Lint/MissingSuper:
  Exclude:
    - 'app/services/api/mobile/operations/**/*'
